# Generated by Django 5.2.7 on 2025-11-05 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_content", models.TextField()),
                (
                    "emotion_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                (
                    "media",
                    models.FileField(
                        blank=True, null=True, upload_to="memories_media/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
